const userRoles = {
  LIBRARIAN: "librarian",
  MEMBER: "member",
};

// constants.js

const genre = [
  { group: "Fiction" },
  { name: "Action and adventure" },
  { name: "Alternate history" },
  { name: "Anthology" },
  { name: "Chick lit" },
  { name: "Children's" },
  { name: "Classic" },
  { name: "Comic book" },
  { name: "Coming-of-age" },
  { name: "Crime" },
  { name: "Drama" },
  { name: "Fairytale" },
  { name: "Fantasy" },
  { name: "Graphic novel" },
  { name: "Historical fiction" },
  { name: "Horror" },
  { name: "Mystery" },
  { name: "Paranormal romance" },
  { name: "Picture book" },
  { name: "Poetry" },
  { name: "Political thriller" },
  { name: "Romance" },
  { name: "Satire" },
  { name: "Science fiction" },
  { name: "Short story" },
  { name: "Suspense" },
  { name: "Thriller" },
  { name: "Western" },
  { name: "Young adult" },

  { group: "Nonfiction" },
  { name: "Art/architecture" },
  { name: "Autobiography" },
  { name: "Biography" },
  { name: "Business/economics" },
  { name: "Crafts/hobbies" },
  { name: "Cookbook" },
  { name: "Diary" },
  { name: "Dictionary" },
  { name: "Encyclopedia" },
  { name: "Guide" },
  { name: "Health/fitness" },
  { name: "History" },
  { name: "Home and garden" },
  { name: "Humor" },
  { name: "Journal" },
  { name: "Math" },
  { name: "Memoir" },
  { name: "Philosophy" },
  { name: "Prayer" },
  { name: "Religion" },
  { name: "Textbook" },
  { name: "True crime" },
  { name: "Review" },
  { name: "Science" },
  { name: "Self help" },
  { name: "Sports" },
  { name: "Travel" },
];

module.exports = { userRoles, genre };
